export const languages = [
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' }
] as const;

export type LanguageCode = typeof languages[number]['code'];

export const translations: Record<LanguageCode, Record<string, string>> = {
  ar: {
    heroTitlePart1: 'تنزيل فيديو تيك توك ',
    heroTitlePart2: 'بدون علامة مائية',
    heroDesc: 'أفضل طريقة لتنزيل مقاطع فيديو TikTok مجاناً وبجودة عالية. لا حاجة لتثبيت أي برامج، فقط انسخ الرابط وحمل!',
    inputPlaceholder: 'ضع رابط فيديو تيك توك هنا...',
    downloadBtn: 'تنزيل',
    processing: 'جاري المعالجة...',
    fetchingData: 'جاري جلب البيانات من الخادم...',
    emptyInputError: 'الرجاء إدخال رابط تيك توك أولاً',
    successMsg: 'تم تجهيز الفيديو بنجاح!',
    termsAgreement: 'من خلال استخدام خدمتنا، فإنك توافق على شروط الاستخدام.',
    videoQuality: 'تحميل الفيديو (جودة عالية / بدون علامة)',
    musicQuality: 'تحميل الموسيقى (MP3)',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الاستخدام',
    allRightsReserved: 'جميع الحقوق محفوظة'
  },
  en: {
    heroTitlePart1: 'Download TikTok Video ',
    heroTitlePart2: 'Without Watermark',
    heroDesc: 'The best way to download TikTok videos for free in high quality. No software needed, just copy the link and download!',
    inputPlaceholder: 'Paste TikTok video link here...',
    downloadBtn: 'Download',
    processing: 'Processing...',
    fetchingData: 'Fetching data from server...',
    emptyInputError: 'Please enter a TikTok link first',
    successMsg: 'Video prepared successfully!',
    termsAgreement: 'By using our service, you agree to our Terms of Use.',
    videoQuality: 'Download Video (HD / No Watermark)',
    musicQuality: 'Download Music (MP3)',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: 'All rights reserved'
  },
  es: {
    heroTitlePart1: 'Descargar Video de TikTok ',
    heroTitlePart2: 'Sin Marca de Agua',
    heroDesc: 'La mejor manera de descargar videos de TikTok gratis en alta calidad. ¡Sin software, solo copia el enlace y descarga!',
    inputPlaceholder: 'Pega el enlace del video aquí...',
    downloadBtn: 'Descargar',
    processing: 'Procesando...',
    fetchingData: 'Obteniendo datos del servidor...',
    emptyInputError: 'Por favor, ingresa un enlace primero',
    successMsg: '¡Video preparado con éxito!',
    termsAgreement: 'Al usar nuestro servicio, aceptas los Términos de Uso.',
    videoQuality: 'Descargar Video (HD / Sin Marca)',
    musicQuality: 'Descargar Música (MP3)',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    allRightsReserved: 'Todos los derechos reservados'
  },
  fr: {
    heroTitlePart1: 'Télécharger une vidéo TikTok ',
    heroTitlePart2: 'Sans Filigrane',
    heroDesc: 'La meilleure façon de télécharger des vidéos TikTok gratuitement en haute qualité. Aucun logiciel requis !',
    inputPlaceholder: 'Collez le lien de la vidéo ici...',
    downloadBtn: 'Télécharger',
    processing: 'Traitement...',
    fetchingData: 'Récupération des données...',
    emptyInputError: 'Veuillez d\'abord entrer un lien TikTok',
    successMsg: 'Vidéo préparée avec succès !',
    termsAgreement: 'En utilisant notre service, vous acceptez les conditions d\'utilisation.',
    videoQuality: 'Télécharger la vidéo (HD / Sans filigrane)',
    musicQuality: 'Télécharger la musique (MP3)',
    privacyPolicy: 'Politique de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    allRightsReserved: 'Tous droits réservés'
  },
  de: {
    heroTitlePart1: 'TikTok Video Herunterladen ',
    heroTitlePart2: 'Ohne Wasserzeichen',
    heroDesc: 'Der beste Weg, um TikTok-Videos kostenlos in hoher Qualität herunterzuladen. Keine Software nötig!',
    inputPlaceholder: 'Fügen Sie den TikTok-Link hier ein...',
    downloadBtn: 'Herunterladen',
    processing: 'Verarbeitung...',
    fetchingData: 'Daten werden abgerufen...',
    emptyInputError: 'Bitte zuerst einen TikTok-Link eingeben',
    successMsg: 'Video erfolgreich vorbereitet!',
    termsAgreement: 'Durch die Nutzung unseres Dienstes stimmen Sie unseren Nutzungsbedingungen zu.',
    videoQuality: 'Video Herunterladen (HD / Ohne)',
    musicQuality: 'Musik Herunterladen (MP3)',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    allRightsReserved: 'Alle Rechte vorbehalten'
  },
  tr: {
    heroTitlePart1: 'TikTok Videosu İndir ',
    heroTitlePart2: 'Filigransız',
    heroDesc: 'TikTok videolarını yüksek kalitede ücretsiz indirmenin en iyi yolu. Yazılıma gerek yok, sadece bağlantıyı yapıştırın!',
    inputPlaceholder: 'TikTok video bağlantısını buraya yapıştırın...',
    downloadBtn: 'İndir',
    processing: 'İşleniyor...',
    fetchingData: 'Sunucudan veriler alınıyor...',
    emptyInputError: 'Lütfen önce bir TikTok bağlantısı girin',
    successMsg: 'Video başarıyla hazırlandı!',
    termsAgreement: 'Hizmetimizi kullanarak Kullanım Şartlarımızı kabul etmiş olursunuz.',
    videoQuality: 'Videoyu İndir (HD / Filigransız)',
    musicQuality: 'Müziği İndir (MP3)',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Hizmet Şartları',
    allRightsReserved: 'Tüm hakları saklıdır'
  },
  zh: {
    heroTitlePart1: '下载 TikTok 视频 ',
    heroTitlePart2: '无水印',
    heroDesc: '免费下载高质量 TikTok 视频的最佳方式。无需安装软件，只需复制链接即可下载！',
    inputPlaceholder: '在此处粘贴 TikTok 视频链接...',
    downloadBtn: '下载',
    processing: '处理中...',
    fetchingData: '正在从服务器获取数据...',
    emptyInputError: '请先输入 TikTok 链接',
    successMsg: '视频准备成功！',
    termsAgreement: '使用我们的服务即表示您同意我们的使用条款。',
    videoQuality: '下载视频 (高清 / 无水印)',
    musicQuality: '下载音乐 (MP3)',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    allRightsReserved: '版权所有'
  },
  ru: {
    heroTitlePart1: 'Скачать видео TikTok ',
    heroTitlePart2: 'Без водяных знаков',
    heroDesc: 'Лучший способ бесплатно скачать видео из TikTok в высоком качестве. Программы не нужны, просто вставьте ссылку!',
    inputPlaceholder: 'Вставьте ссылку на видео TikTok здесь...',
    downloadBtn: 'Скачать',
    processing: 'Обработка...',
    fetchingData: 'Получение данных с сервера...',
    emptyInputError: 'Пожалуйста, введите ссылку на TikTok',
    successMsg: 'Видео успешно подготовлено!',
    termsAgreement: 'Используя наш сервис, вы соглашаетесь с Условиями использования.',
    videoQuality: 'Скачать видео (HD / Без знака)',
    musicQuality: 'Скачать музыку (MP3)',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfService: 'Условия использования',
    allRightsReserved: 'Все права защищены'
  },
  hi: {
    heroTitlePart1: 'टिकटॉक वीडियो डाउनलोड करें ',
    heroTitlePart2: 'बिना वॉटरमार्क के',
    heroDesc: 'उच्च गुणवत्ता में मुफ्त में टिकटॉक वीडियो डाउनलोड करने का सबसे अच्छा तरीका। कोई सॉफ्टवेयर नहीं चाहिए!',
    inputPlaceholder: 'यहाँ टिकटॉक वीडियो लिंक पेस्ट करें...',
    downloadBtn: 'डाउनलोड',
    processing: 'प्रक्रिया हो रही है...',
    fetchingData: 'सर्वर से डेटा प्राप्त किया जा रहा है...',
    emptyInputError: 'कृपया पहले एक टिकटॉक लिंक दर्ज करें',
    successMsg: 'वीडियो सफलतापूर्वक तैयार किया गया!',
    termsAgreement: 'हमारी सेवा का उपयोग करके, आप हमारी उपयोग की शर्तों से सहमत होते हैं।',
    videoQuality: 'वीडियो डाउनलोड करें (HD / कोई वॉटरमार्क नहीं)',
    musicQuality: 'संगीत डाउनलोड करें (MP3)',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    allRightsReserved: 'सर्वाधिकार सुरक्षित'
  },
  pt: {
    heroTitlePart1: 'Baixar Vídeo do TikTok ',
    heroTitlePart2: 'Sem Marca D\'água',
    heroDesc: 'A melhor forma de baixar vídeos do TikTok grátis em alta qualidade. Nenhum software necessário!',
    inputPlaceholder: 'Cole o link do vídeo do TikTok aqui...',
    downloadBtn: 'Baixar',
    processing: 'Processando...',
    fetchingData: 'Buscando dados do servidor...',
    emptyInputError: 'Por favor, insira um link do TikTok primeiro',
    successMsg: 'Vídeo preparado com sucesso!',
    termsAgreement: 'Ao usar nosso serviço, você concorda com nossos Termos de Uso.',
    videoQuality: 'Baixar Vídeo (HD / Sem Marca)',
    musicQuality: 'Baixar Música (MP3)',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    allRightsReserved: 'Todos os direitos reservados'
  }
};
