export const languages = [
  { code: 'ar', name: 'العربية', country: 'sa' },
  { code: 'en', name: 'English', country: 'us' },
  { code: 'es', name: 'Español', country: 'es' },
  { code: 'fr', name: 'Français', country: 'fr' },
  { code: 'de', name: 'Deutsch', country: 'de' },
  { code: 'tr', name: 'Türkçe', country: 'tr' },
  { code: 'zh', name: '中文', country: 'cn' },
  { code: 'ru', name: 'Русский', country: 'ru' },
  { code: 'hi', name: 'हिन्दी', country: 'in' },
  { code: 'pt', name: 'Português', country: 'br' }
] as const;

export type LanguageCode = typeof languages[number]['code'];

export const translations: Record<LanguageCode, Record<string, string>> = {
  ar: {
    heroTitlePart1: 'تنزيل فيديو تيك توك ',
    heroTitlePart2: 'بدون علامة مائية',
    heroDesc: 'أفضل طريقة لتنزيل مقاطع فيديو TikTok مجاناً وبجودة عالية. لا حاجة لتثبيت أي برامج، فقط انسخ الرابط وحمل!',
    inputPlaceholder: 'ضع رابط فيديو تيك توك هنا...',
    downloadBtn: 'تنزيل',
    processing: 'جاري المعالجة...',
    fetchingData: 'جاري جلب البيانات من الخادم...',
    emptyInputError: 'الرجاء إدخال رابط تيك توك أولاً',
    successMsg: 'تم تجهيز الفيديو بنجاح!',
    termsAgreement: 'من خلال استخدام خدمتنا، فإنك توافق على <a class="text-blue-500 hover:underline" href="/terms-of-service">شروط الاستخدام</a>.',
    videoQuality: 'تحميل الفيديو (جودة عالية / بدون علامة)',
    musicQuality: 'تحميل الموسيقى (MP3)',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الاستخدام',
    allRightsReserved: 'جميع الحقوق محفوظة',
    footerDesc: 'أفضل أداة مجانية لتنزيل فيديوهات تيك توك بدون علامة مائية.',
    historyTitle: 'سجل التحميلات',
    clearHistory: 'مسح الكل',
    removeFromHistoryAria: 'حذف من السجل',
    reDownload: 'إعادة التحميل',
    featuresTitle: 'لماذا تختار SavePro لتحميل فيديوهات تيك توك؟',
    featuresDesc: 'أفضل أداة تحميل تيك توك مجانية مع مميزات متقدمة لتحميل فيديوهات تيك توك بسهولة',
    featureFastTitle: 'تحميل سريع',
    featureFastDesc: 'تحميل فيديوهات تيك توك بسرعة فائقة بدون انتظار طويل',
    featureNoWatermarkTitle: 'بدون علامة مائية',
    featureNoWatermarkDesc: 'احصل على فيديوهات تيك توك نظيفة بدون أي علامات مائية',
    featureMusicTitle: 'تحميل الموسيقى',
    featureMusicDesc: 'قم بتحميل موسيقى تيك توك بتنسيق MP3 بجودة عالية',
    howItWorksTitle: 'كيفية تحميل فيديوهات تيك توك',
    howItWorksDesc: 'خطوات بسيطة لتحميل أي فيديو من تيك توك باستخدام موقعنا',
    step1Title: 'انسخ الرابط',
    step1Desc: 'انسخ رابط الفيديو من تطبيق تيك توك أو الموقع',
    step2Title: 'ألصق الرابط',
    step2Desc: 'الصق الرابط في مربع البحث في موقع SavePro',
    step3Title: 'تحميل الفيديو',
    step3Desc: 'اضغط على زر التحميل واحصل على الفيديو فوراً',
    faqTitle: 'الأسئلة الشائعة',
    faqDesc: 'إجابات على أكثر الأسئلة شيوعاً حول استخدام SavePro',
    faq1Q: 'هل أداة SavePro مجانية؟',
    faq1A: 'نعم، موقع SavePro مجاني بالكامل ولن يطلب منك أي رسوم لتنزيل الفيديوهات.',
    faq2Q: 'هل يمكنني تنزيل مقاطع فيديو TikTok على أجهزة iPhone / iPad؟',
    faq2A: 'نعم بالتأكيد. إذا كنت تستخدم نظام iOS، نوصي باستخدام متصفح Safari لإجراء التنزيل بسهولة.',
    faq3Q: 'هل أقوم بتنزيل الفيديوهات بدون علامة مائية فعلاً؟',
    faq3A: 'نعم، الميزة الأساسية لموقعنا هي إزالة العلامة المائية وشعار تيك توك من الفيديو ليظهر بشكل نقي.',
    faq4Q: 'هل أحتاج لتثبيت أي برنامج أو تطبيق؟',
    faq4A: 'لا، SavePro يعمل مباشرة من المتصفح. لا تحتاج لتثبيت أي شيء على جهازك.',
    faq5Q: 'ما هي جودة الفيديو الذي أقوم بتحميله؟',
    faq5A: 'يتم تحميل الفيديوهات بأعلى جودة متاحة من خوادم TikTok، عادة بدقة HD أو Full HD.',
    historyCleared: 'تم مسح السجل',
    videoNotAvailable: 'رابط الفيديو غير متوفر',
    musicNotAvailable: 'رابط الموسيقى غير متوفر',
    downloadingVideo: 'جاري تحميل الفيديو...',
    downloadingMusic: 'جاري تحميل الموسيقى...',
    downloadFailed: 'فشل التحميل (HTTP {status})',
    fileTooSmall: 'الملف المحمّل صغير جداً — قد يكون الرابط منتهي الصلاحية',
    downloadSuccess: 'تم التحميل بنجاح!',
    downloadFailedGeneric: 'فشل التحميل، حاول مجدداً',
    loading: 'جاري التحميل...',
    privacyPolicyTitle: 'سياسة الخصوصية',
    privacyPolicyIntro: 'في SavePro، نلتزم بحماية خصوصيتك وضمان تجربة آمنة. توضح هذه السياسة كيف نتعامل مع البيانات وفقًا للمعايير العالمية (GDPR).',
    privacySec1Title: '1. عدم الاحتفاظ بالبيانات',
    privacySec1Content: 'نحن نتبع سياسة صارمة لعدم الاحتفاظ بالبيانات. لا نقوم بتخزين فيديوهات تيك توك، أو سجلات التحميل، أو أي معلومات شخصية على خوادمنا.',
    privacySec2Title: '2. واجهات البرمجيات والأطراف الثالثة',
    privacySec2Content: 'تتعامل خدمتنا مع واجهات برمجة تطبيقات (APIs) خارجية لجلب المحتوى. نستخدم Google AdSense لعرض الإعلانات، والتي قد تجمع بيانات تقنية لتحسين تجربتك.',
    privacySec3Title: '3. ملفات تعريف الارتباط (Cookies)',
    privacySec3Content: 'نستخدم الكوكيز لتشغيل الموقع وعرض إعلانات مخصصة. يمكنك إدارة تفضيلات الكوكيز من خلال إعدادات متصفحك.',
    privacySec4Title: '4. الامتثال للخصوصية',
    privacySec4Content: 'نحن نلتزم بالقوانين الدولية لحماية البيانات. خدمتنا مصممة لتكون مجهولة الهوية بالكامل لضمان أقصى درجات الخصوصية.',
    privacySec5Title: '5. الإعلانات والروابط',
    privacySec5Content: 'قد يحتوي موقعنا على إعلانات من Google AdSense. هؤلاء الشركاء قد يستخدمون ملفات تعريف الارتباط لتقديم إعلانات بناءً على زياراتك السابقة.',
    privacySec6Title: '6. التحديثات القانونية',
    privacySec6Content: 'نحتفظ بالحق في تحديث هذه السياسة لضمان استمرار الامتثال للمعايير القانونية والتقنية.',
    privacyContactTitle: 'الدعم القانوني',
    privacyContactContent: 'لأية استفسارات تتعلق بالخصوصية أو الشروط، تواصل معنا:',
    termsTitle: 'شروط الخدمة',
    termsIntro: 'باستخدام SavePro، فإنك تقر وتوافق على الشروط التالية المصممة لحماية حقوق الملكية والنزاهة القانونية.',
    termsSec1Title: '1. إخلاء مسؤولية: عدم التبعية لـ TikTok',
    termsSec1Content: 'SavePro هو موقع مستقل ولا يتبع بأي شكل من الأشكال شركة TikTok أو ByteDance Ltd. نحن نوفر أداة تقنية فقط.',
    termsSec2Title: '2. سياسة الاستخدام العادل',
    termsSec2Content: 'هذه الأداة مخصصة للاستخدام الشخصي وغير التجاري فقط. يجب على المستخدمين احترام حقوق الطبع والنشر للمبدعين الأصليين.',
    termsSec3Title: '3. مسؤولية المستخدم',
    termsSec3Content: 'يتحمل المستخدم المسؤولية الكاملة عن المحتوى الذي يقوم بتحميله. نحن لا نستضيف أي محتوى ولا نتحمل مسؤولية أي سوء استخدام.',
    termsSec4Title: '4. حدود المسؤولية',
    termsSec4Content: 'يتم تقديم الخدمة "كما هي" دون ضمانات. نحن غير مسؤولين عن أي أضرار ناتجة عن استخدام الأداة.',
    termsSec5Title: '5. الموافقة القانونية',
    termsSec5Content: 'استمرارك في استخدام الموقع يعني موافقتك الصريحة على هذه الشروط والأحكام.',
    fetchError: 'فشل جلب بيانات الفيديو. تأكد من الرابط وحاول مجدداً.',
    privateVideoError: 'هذا الفيديو خاص ولا يمكن تحميله.',
    deletedVideoError: 'يبدو أن الفيديو قد تم حذفه.',
    invalidUrlError: 'الرابط غير صحيح، يرجى إدخال رابط تيك توك صحيح.',
    rateLimitError: 'لقد تجاوزت حد الطلبات المسموح به. يرجى الانتظار قليلاً.',
    serverError: 'حدث خطأ في الخادم، يرجى المحاولة مرة أخرى لاحقاً.',
    connectionError: 'فشل الاتصال بالخادم ({status}).',
    invalidResponseError: 'استجابة غير صالحة من الخادم. حاول مرة أخرى.',
    footerAbout: 'أفضل أداة مجانية لتنزيل فيديوهات تيك توك بدون علامة مائية. سريعة، مجانية وآمنة.',
    quickLinks: 'روابط سريعة',
    home: 'الرئيسية',
    features: 'المميزات',
    howToUse: 'طريقة الاستخدام',
    faq: 'الأسئلة الشائعة',
    legal: 'قانوني',
    dmca: 'حقوق الطبع والنشر (DMCA)',
    support: 'الدعم',
    contactUs: 'اتصل بنا',
    secureConnection: 'اتصال آمن',
    operational: 'الأنظمة تعمل بكفاءة',
    rightsReserved: 'جميع الحقوق محفوظة.',
    version: 'الإصدار',
    dmcaTitle: 'حقوق الطبع والنشر (DMCA)',
    dmcaIntro: 'نحن نحترم حقوق الملكية الفكرية للآخرين ونطلب من مستخدمينا فعل الشيء نفسه.',
    dmcaSec1Title: 'إشعار بعدم استضافة المحتوى',
    dmcaSec1Content: 'موقع SavePro لا يستضيف أي فيديوهات أو ملفات على خوادمه الخاصة. خدمتنا تعمل فقط كوسيط تقني لتنزيل المحتوى من خوادم المنصات الأصلية.',
    contactTitle: 'تواصل معنا',
    contactDesc: 'لديك سؤال أو تحتاج إلى دعم فني؟ فريقنا هنا لمساعدتك على مدار الساعة.',
    fullName: 'الاسم الكامل',
    emailAddress: 'البريد الإلكتروني',
    emailUs: 'راسلنا عبر البريد',
    subject: 'الموضوع',
    message: 'الرسالة',
    sendMessage: 'إرسال الرسالة',
    messageSent: 'تم إرسال الرسالة!',
    messageSentDesc: 'شكراً لتواصلك معنا. سنرد عليك في أقرب وقت ممكن.',
    sendAnother: 'إرسال رسالة أخرى',
    lightMode: 'تفعيل الوضع النهاري',
    darkMode: 'تفعيل الوضع الليلي',
    unexpectedError: 'استجابة غير متوقعة من الخادم.',
    emptyFileError: 'الملف المستلم فارغ.',
    downloadStartedVideo: 'تم بدء تحميل الفيديو',
    downloadStartedMusic: 'تم بدء تحميل الموسيقى',
    downloadErrorVideo: 'تعذر تحميل الفيديو: تحقق من اتصالك بالإنترنت وحاول مرة أخرى.',
    downloadErrorMusic: 'تعذر تحميل الموسيقى: تحقق من اتصالك بالإنترنت وحاول مرة أخرى.',
    downloadTimeout: 'انتهت مهلة التحميل. حاول مرة أخرى.',
    downloadingVideoAria: 'جاري تحميل الفيديو',
    downloadingMusicAria: 'جاري تحميل الموسيقى',
    aboutUsTitle: 'من نحن',
    aboutUsStory: 'قصتنا',
    aboutUsStoryContent: 'تأسست SavePro لسد الفجوة في أدوات تحميل المحتوى الرقمي، مع التركيز الكامل على السرعة والخصوصية. نحن فريق من المطورين المهتمين بتوفير تجربة مستخدم سلسة وعالية الأداء.',
    aboutUsMission: 'مهمتنا',
    aboutUsMissionContent: 'تتمثل مهمتنا في توفير أداة تحميل تيك توك الأكثر موثوقية في العالم، مع ضمان أن تظل بيانات المستخدمين آمنة ومجهولة تماماً.',
    aboutUsPrivacyExcellence: 'التميز في الخصوصية',
    aboutUsPrivacyExcellenceContent: 'نحن نؤمن بأن الخصوصية حق أساسي، لذا صممنا SavePro ليعمل بدون الحاجة لأي تسجيل بيانات أو تتبع.',
    disclaimerTitle: 'إخلاء المسؤولية',
    disclaimerMain: 'تنبيه قانوني هام',
    disclaimerContent: 'يتم توفير SavePro كأداة تقنية فقط. نحن لا نستضيف أي محتوى على خوادمنا. المستخدم هو المسؤول الوحيد عن كيفية استخدام الأداة والتأكد من توافق استخدامه مع قوانين الملكية الفكرية المحلية والدولية.',
    disclaimerTikTok: 'نحن لسنا تابعين لشركة TikTok أو ByteDance. استخدامه للأداة يعني اعترافك بأنك تملك الحقوق اللازمة لتحميل المحتوى.',
  },
  en: {
    heroTitlePart1: 'Download TikTok Video ',
    heroTitlePart2: 'Without Watermark',
    heroDesc: 'The best way to download TikTok videos for free in high quality. No software needed, just copy the link and download!',
    inputPlaceholder: 'Paste TikTok video link here...',
    downloadBtn: 'Download',
    processing: 'Processing...',
    fetchingData: 'Fetching data from server...',
    emptyInputError: 'Please enter a TikTok link first',
    successMsg: 'Video prepared successfully!',
    termsAgreement: 'By using our service, you agree to our <a class="text-blue-500 hover:underline" href="/terms-of-service">Terms of Use</a>.',
    videoQuality: 'Download Video (HD / No Watermark)',
    musicQuality: 'Download Music (MP3)',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: 'All rights reserved',
    footerDesc: 'The best free tool to download TikTok videos without watermark.',
    historyTitle: 'Download History',
    clearHistory: 'Clear All',
    removeFromHistoryAria: 'Remove from history',
    reDownload: 'Re-download',
    featuresTitle: 'Why choose SavePro for TikTok downloads?',
    featuresDesc: 'The best free TikTok downloader with advanced features.',
    featureFastTitle: 'Fast Download',
    featureFastDesc: 'Super fast downloads without long waiting times.',
    featureNoWatermarkTitle: 'No Watermark',
    featureNoWatermarkDesc: 'Get clean TikTok videos without any watermarks.',
    featureMusicTitle: 'Download Music',
    featureMusicDesc: 'Download TikTok music in high-quality MP3 format.',
    howItWorksTitle: 'How to download TikTok videos?',
    howItWorksDesc: 'Simple steps to download any video using SavePro.',
    step1Title: 'Copy Link',
    step1Desc: 'Copy the video link from TikTok app or website.',
    step2Title: 'Paste Link',
    step2Desc: 'Paste the link in the SavePro search box.',
    step3Title: 'Download Video',
    step3Desc: 'Click download and get your video instantly.',
    faqTitle: 'FAQ',
    faqDesc: 'Answers to common questions about SavePro.',
    faq1Q: 'Is SavePro free?',
    faq1A: 'Yes, SavePro is completely free and won\'t ask for any fees.',
    faq2Q: 'Can I download on iPhone/iPad?',
    faq2A: 'Yes! If you are on iOS, we recommend using Safari for easy downloads.',
    faq3Q: 'Is it really without watermark?',
    faq3A: 'Yes, our main feature is removing the watermark completely.',
    faq4Q: 'Do I need to install anything?',
    faq4A: 'No, SavePro works directly in the browser.',
    faq5Q: 'What is the video quality?',
    faq5A: 'Videos are downloaded in the highest available quality (HD).',
    historyCleared: 'History cleared',
    videoNotAvailable: 'Video link not available',
    musicNotAvailable: 'Music link not available',
    downloadingVideo: 'Downloading video...',
    downloadingMusic: 'Downloading music...',
    downloadFailed: 'Download failed (HTTP {status})',
    fileTooSmall: 'File too small — link might be expired',
    downloadSuccess: 'Downloaded successfully!',
    downloadFailedGeneric: 'Download failed, try again',
    loading: 'Loading...',
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyIntro: 'SavePro ("we", "us", "our") is committed to protecting user privacy while providing a high-performance TikTok downloading service. This policy is GDPR and CCPA compliant.',
    privacySec1Title: '1. Data Non-Retention Policy',
    privacySec1Content: 'We operate on a strict data non-retention policy. We do not store TikTok videos, download history, or personal identifiers on our servers.',
    privacySec2Title: '2. APIs & Third-Party Services',
    privacySec2Content: 'Our service interfaces with third-party APIs to retrieve media. We use Google AdSense for monetization, which may collect technical data as outlined in their privacy policies.',
    privacySec3Title: '3. Cookie & Tracking Policy',
    privacySec3Content: 'We use essential cookies for site functionality and third-party cookies (Google AdSense) to serve personalized advertisements and analyze traffic.',
    privacySec4Title: '4. User Rights & Data Protection',
    privacySec4Content: 'Users have the right to access, rectify, or request deletion of any temporarily processed data. Our service is designed to be privacy-first and anonymous.',
    privacySec5Title: '5. Advertising Partners',
    privacySec5Content: 'Third-party vendors, including Google, use cookies to serve ads based on a user\'s prior visits to your website or other websites.',
    privacySec6Title: '6. Policy Updates',
    privacySec6Content: 'We reserve the right to update this policy to reflect changes in legal or technical requirements.',
    privacyContactTitle: 'Legal & Support',
    privacyContactContent: 'For any inquiries regarding our privacy practices or terms, contact us at:',
    termsTitle: 'Terms of Service',
    termsIntro: 'By accessing SavePro, you agree to these legally binding terms designed to ensure fair use and legal compliance.',
    termsSec1Title: '1. Non-Affiliation with TikTok',
    termsSec1Content: 'SavePro is an independent tool and is NOT affiliated, associated, authorized, or endorsed by TikTok, ByteDance Ltd, or its subsidiaries.',
    termsSec2Title: '2. Fair Use & Copyright Compliance',
    termsSec2Content: 'This tool is for personal, non-commercial use only. Users must respect the intellectual property rights of content creators and comply with copyright laws.',
    termsSec3Title: '3. User Responsibility & Liability',
    termsSec3Content: 'Users are solely responsible for the content they download. SavePro does not host media and is not liable for any copyright infringements or misuse.',
    termsSec4Title: '4. Disclaimer of Warranties',
    termsSec4Content: 'The service is provided "as is" without any warranties. We do not guarantee uninterrupted service or specific outcomes from using the tool.',
    termsSec5Title: '5. Legal Agreement',
    termsSec5Content: 'Continued use of the site constitutes your express agreement to these terms and any future modifications.',
    fetchError: 'Failed to fetch video data. Please check the link and try again.',
    privateVideoError: 'This video is private and cannot be downloaded.',
    deletedVideoError: 'It seems this video has been deleted.',
    invalidUrlError: 'Invalid URL. Please enter a valid TikTok link.',
    rateLimitError: 'Rate limit exceeded. Please wait a moment.',
    serverError: 'Server error. Please try again later.',
    connectionError: 'Connection to server failed ({status}).',
    invalidResponseError: 'Invalid response from server. Please try again.',
    footerAbout: 'Premium TikTok video downloader. Download high-quality videos without watermark instantly. Fast, free, and secure.',
    quickLinks: 'Quick Links',
    home: 'Home',
    features: 'Features',
    howToUse: 'How to Use',
    faq: 'FAQ',
    legal: 'Legal',
    dmca: 'DMCA Compliance',
    support: 'Support',
    contactUs: 'Contact Us',
    secureConnection: 'Secure Connection',
    operational: 'Systems Operational',
    rightsReserved: 'All Rights Reserved.',
    version: 'Version',
    dmcaTitle: 'DMCA Compliance',
    dmcaIntro: 'We respect the intellectual property rights of others and expect our users to do the same.',
    dmcaSec1Title: 'Content Non-Hosting Statement',
    dmcaSec1Content: 'SavePro.site does not host any copyrighted media, videos, or files on its own servers. Our service acts strictly as a technical service provider.',
    contactTitle: 'Get in Touch',
    contactDesc: 'Have a question or need technical support? Our team is here to help you 24/7.',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    emailUs: 'Email Us',
    subject: 'Subject',
    message: 'Message',
    sendMessage: 'Send Message',
    messageSent: 'Message Sent!',
    messageSentDesc: 'Thank you for reaching out. We will get back to you within 24 hours.',
    sendAnother: 'Send Another',
    lightMode: 'Switch to Light Mode',
    darkMode: 'Switch to Dark Mode',
    unexpectedError: 'Unexpected response from server.',
    emptyFileError: 'The received file is empty.',
    downloadStartedVideo: 'Video download started',
    downloadStartedMusic: 'Music download started',
    downloadErrorVideo: 'Could not download video: check your internet and try again.',
    downloadErrorMusic: 'Could not download music: check your internet and try again.',
    downloadTimeout: 'Download timed out. Please try again.',
    downloadingVideoAria: 'Downloading video...',
    downloadingMusicAria: 'Downloading music...',
    aboutUsTitle: 'About Us',
    aboutUsStory: 'Our Story',
    aboutUsStoryContent: 'SavePro was born out of a desire to create the most efficient, privacy-focused media tool on the web. Our team is dedicated to technical excellence and user empowerment.',
    aboutUsMission: 'Our Mission',
    aboutUsMissionContent: 'To provide a seamless, high-definition downloading experience that respects intellectual property and user privacy above all else.',
    aboutUsPrivacyExcellence: 'Privacy Excellence',
    aboutUsPrivacyExcellenceContent: 'We believe privacy is a right. SavePro is designed to function without tracking, registration, or data storage, ensuring your digital footprint remains clean.',
    disclaimerTitle: 'Disclaimer',
    disclaimerMain: 'Legal Disclaimer',
    disclaimerContent: 'SavePro provides a technical service for downloading publicly available media. We do not host, store, or redistribute any content. The user assumes full responsibility for the use of this tool.',
    disclaimerTikTok: 'We are not affiliated with TikTok or ByteDance. Users must ensure they have the legal right to download any content retrieved through our service.',
  },
  es: {
    heroTitlePart1: 'Descargar Video de TikTok ',
    heroTitlePart2: 'Sin Marca de Agua',
    heroDesc: 'La mejor manera de descargar videos de TikTok gratis en alta calidad. ¡Sin software, solo copia el enlace y descarga!',
    inputPlaceholder: 'Pega el enlace del video aquí...',
    downloadBtn: 'Descargar',
    processing: 'Procesando...',
    fetchingData: 'Obteniendo datos del servidor...',
    emptyInputError: 'Por favor, ingresa un enlace primero',
    successMsg: '¡Video preparado con éxito!',
    termsAgreement: 'Al usar nuestro servicio, aceptas los <a class="text-blue-500 hover:underline" href="/terms-of-service">Términos de Uso</a>.',
    videoQuality: 'Descargar Video (HD / Sin Marca)',
    musicQuality: 'Descargar Música (MP3)',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    allRightsReserved: 'Todos los derechos reservados',
    footerDesc: 'La mejor herramienta gratuita para descargar videos de TikTok sin marca de agua.',
    historyTitle: 'Historial de Descargas',
    clearHistory: 'Borrar Todo',
    removeFromHistoryAria: 'Eliminar del historial',
    reDownload: 'Volver a descargar',
    featuresTitle: '¿Por qué elegir SavePro para descargas de TikTok?',
    featuresDesc: 'El mejor descargador gratuito de TikTok con funciones avanzadas.',
    featureFastTitle: 'Descarga Rápida',
    featureFastDesc: 'Descargas súper rápidas sin largos tiempos de espera.',
    featureNoWatermarkTitle: 'Sin Marca de Agua',
    featureNoWatermarkDesc: 'Obtén videos de TikTok limpios sin ninguna marca de agua.',
    featureMusicTitle: 'Descargar Música',
    featureMusicDesc: 'Descarga música de TikTok en formato MP3 de alta calidad.',
    howItWorksTitle: '¿Cómo descargar videos de TikTok?',
    howItWorksDesc: 'Pasos sencillos para descargar cualquier video usando SavePro.',
    step1Title: 'Copiar Enlace',
    step1Desc: 'Copia el enlace del video desde la aplicación o sitio web de TikTok.',
    step2Title: 'Pegar Enlace',
    step2Desc: 'Pega el enlace en el cuadro de búsqueda de SavePro.',
    step3Title: 'Descargar Video',
    step3Desc: 'Haz clic en descargar y obtén tu video al instante.',
    faqTitle: 'Preguntas Frecuentes',
    faqDesc: 'Respuestas a preguntas comunes sobre SavePro.',
    faq1Q: '¿Es SavePro gratis?',
    faq1A: 'Sí, SavePro es completamente gratuito y no te pedirá ninguna tarifa.',
    faq2Q: '¿Puedo descargar en iPhone/iPad?',
    faq2A: '¡Sí! Si estás en iOS, recomendamos usar Safari para descargas fáciles.',
    faq3Q: '¿Es realmente sin marca de agua?',
    faq3A: 'Sí, nuestra función principal es eliminar la marca de agua por completo.',
    faq4Q: '¿Necesito instalar algo?',
    faq4A: 'No, SavePro funciona directamente en el navegador.',
    faq5Q: '¿Cuál es la calidad del video?',
    faq5A: 'Los videos se descargan en la mejor calidad disponible (HD).',
    historyCleared: 'Historial borrado',
    videoNotAvailable: 'Enlace de video no disponible',
    musicNotAvailable: 'Enlace de música no disponible',
    downloadingVideo: 'Descargando video...',
    downloadingMusic: 'Descargando música...',
    downloadFailed: 'Error de descarga (HTTP {status})',
    fileTooSmall: 'Archivo demasiado pequeño; el enlace podría haber expirado',
    downloadSuccess: '¡Descargado con éxito!',
    downloadFailedGeneric: 'Descarga fallida, intenta de nuevo',
    loading: 'Cargando...',
    privacyPolicyTitle: 'Política de Privacidad',
    privacyPolicyIntro: 'En SavePro, nos comprometemos a proteger y respetar su privacidad. Esta política explica cómo recopilamos y usamos la información.',
    privacySec1Title: '1. Información que Recopilamos',
    privacySec1Content: 'No recopilamos información personal como nombre o correo electrónico. Podemos recopilar datos no personales como la dirección IP y el tipo de navegador.',
    privacySec2Title: '2. Cómo Usamos su Información',
    privacySec2Content: 'La información se utiliza para mejorar la calidad del servicio y garantizar la seguridad del sitio.',
    privacySec3Title: '3. Cookies',
    privacySec3Content: 'Utilizamos cookies para mejorar la experiencia del usuario y mostrar anuncios personalizados.',
    privacySec4Title: '4. Compartir Información',
    privacySec4Content: 'No compartimos su información con terceros, excepto según lo exija la ley.',
    privacySec5Title: '5. Anuncios y Enlaces Externos',
    privacySec5Content: 'Nuestro sitio puede contener anuncios de Google AdSense y enlaces a sitios externos.',
    privacySec6Title: '6. Cambios en la Política',
    privacySec6Content: 'Nos reservamos el derecho de actualizar esta política en cualquier momento.',
    privacyContactTitle: 'Contáctenos',
    privacyContactContent: 'Si tiene alguna pregunta, contáctenos en:',
    termsTitle: 'Términos de Servicio',
    termsIntro: 'Al usar SavePro, usted acepta estos términos y condiciones.',
    termsSec1Title: '1. Naturaleza del Servicio',
    termsSec1Content: 'SavePro es una herramienta gratuita para descargar videos de TikTok solo para uso personal.',
    termsSec2Title: '2. Propiedad Intelectual',
    termsSec2Content: 'Los derechos de autor pertenecen a los propietarios del contenido original. Se debe obtener permiso antes de descargar.',
    termsSec3Title: '3. Uso Permitido',
    termsSec3Content: 'Se prohíbe el uso de bots o la sobrecarga de servidores.',
    termsSec4Title: '4. Descargo de Responsabilidad',
    termsSec4Content: 'El servicio se proporciona "tal cual" sin garantías.',
    termsSec5Title: '5. Cambios',
    termsSec5Content: 'Nos reservamos el derecho de modificar estos términos en cualquier momento.'
  },
  fr: {
    heroTitlePart1: 'Télécharger une vidéo TikTok ',
    heroTitlePart2: 'Sans Filigrane',
    heroDesc: 'La meilleure façon de télécharger des vidéos TikTok gratuitement en haute qualité. Aucun logiciel requis !',
    inputPlaceholder: 'Collez le lien de la vidéo ici...',
    downloadBtn: 'Télécharger',
    processing: 'Traitement...',
    fetchingData: 'Récupération des données...',
    emptyInputError: 'Veuillez d\'abord entrer un lien TikTok',
    successMsg: 'Vidéo préparée avec succès !',
    termsAgreement: 'En utilisant notre service, vous acceptez <a class="text-blue-500 hover:underline" href="/terms-of-service">les conditions d\'utilisation</a>.',
    videoQuality: 'Télécharger la vidéo (HD / Sans filigrane)',
    musicQuality: 'Télécharger la musique (MP3)',
    privacyPolicy: 'Politique de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    allRightsReserved: 'Tous droits réservés',
    footerDesc: 'Le meilleur outil gratuit pour télécharger des vidéos TikTok sans filigrane.',
    historyTitle: 'Historique des téléchargements',
    clearHistory: 'Tout effacer',
    removeFromHistoryAria: 'Supprimer de l\'historique',
    reDownload: 'Re-télécharger',
    featuresTitle: 'Pourquoi choisir SavePro pour les téléchargements TikTok ?',
    featuresDesc: 'Le meilleur téléchargeur TikTok gratuit avec des fonctionnalités avancées.',
    featureFastTitle: 'Téléchargement rapide',
    featureFastDesc: 'Téléchargements ultra-rapides sans longs délais d\'attente.',
    featureNoWatermarkTitle: 'Sans filigrane',
    featureNoWatermarkDesc: 'Obtenez des vidéos TikTok propres sans aucun filigrane.',
    featureMusicTitle: 'Télécharger de la musique',
    featureMusicDesc: 'Téléchargez de la musique TikTok au format MP3 de haute qualité.',
    howItWorksTitle: 'Comment télécharger des vidéos TikTok ?',
    howItWorksDesc: 'Étapes simples pour télécharger n\'importe quelle vidéo en utilisant SavePro.',
    step1Title: 'Copier le lien',
    step1Desc: 'Copiez le lien de la vidéo depuis l\'application ou le site Web TikTok.',
    step2Title: 'Coller le lien',
    step2Desc: 'Collez le lien dans la zone de recherche SavePro.',
    step3Title: 'Télécharger la vidéo',
    step3Desc: 'Cliquez sur télécharger et obtenez votre vidéo instantanément.',
    faqTitle: 'FAQ',
    faqDesc: 'Réponses aux questions courantes sur SavePro.',
    faq1Q: 'Est-ce que SavePro est gratuit ?',
    faq1A: 'Oui, SavePro est totalement gratuit et ne demandera aucun frais.',
    faq2Q: 'Puis-je télécharger sur iPhone/iPad ?',
    faq2A: 'Oui ! Si vous êtes sur iOS, nous vous recommandons d\'utiliser Safari pour des téléchargements faciles.',
    faq3Q: 'Est-ce vraiment sans filigrane ?',
    faq3A: 'Oui, notre principale caractéristique est de supprimer complètement le filigrane.',
    faq4Q: 'Dois-je installer quelque chose ?',
    faq4A: 'Non, SavePro fonctionne directement dans le navigateur.',
    faq5Q: 'Quelle est la qualité de la vidéo ?',
    faq5A: 'Les vidéos sont téléchargées dans la meilleure qualité disponible (HD).',
    historyCleared: 'Historique effacé',
    videoNotAvailable: 'Lien vidéo non disponible',
    musicNotAvailable: 'Lien musique non disponible',
    downloadingVideo: 'Téléchargement de la vidéo...',
    downloadingMusic: 'Téléchargement de la musique...',
    downloadFailed: 'Échec du téléchargement (HTTP {status})',
    fileTooSmall: 'Fichier trop petit - le lien a peut-être expiré',
    downloadSuccess: 'Téléchargé avec succès !',
    downloadFailedGeneric: 'Échec du téléchargement, réessayez',
    loading: 'Chargement...',
    privacyPolicyTitle: 'Politique de confidentialité',
    privacyPolicyIntro: 'Chez SavePro, nous nous engageons à protéger et respecter votre vie privée. Cette politique explique comment nous collectons et utilisons les informations.',
    privacySec1Title: '1. Informations que nous collectons',
    privacySec1Content: 'Nous ne collectons pas d\'informations personnelles telles que le nom ou l\'e-mail. Nous pouvons collecter des données non personnelles comme l\'adresse IP et le type de navigateur.',
    privacySec2Title: '2. Comment nous utilisons vos informations',
    privacySec2Content: 'Les informations sont utilisées pour améliorer la qualité du service et assurer la sécurité du site.',
    privacySec3Title: '3. Cookies',
    privacySec3Content: 'Nous utilisons des cookies pour améliorer l\'expérience utilisateur et afficher des publicités personnalisées.',
    privacySec4Title: '4. Partage d\'informations',
    privacySec4Content: 'Nous ne partageons pas vos informations avec des tiers, sauf si la loi l\'exige.',
    privacySec5Title: '5. Publicités et liens externes',
    privacySec5Content: 'Notre site peut contenir des publicités de Google AdSense et des liens vers des sites externes.',
    privacySec6Title: '6. Modifications de la politique',
    privacySec6Content: 'Nous nous réservons le droit de mettre à jour cette politique à tout moment.',
    privacyContactTitle: 'Contactez-nous',
    privacyContactContent: 'Si vous avez des questions, contactez-nous à :',
    termsTitle: 'Conditions d\'utilisation',
    termsIntro: 'En utilisant SavePro, vous acceptez ces conditions générales.',
    termsSec1Title: '1. Nature du service',
    termsSec1Content: 'SavePro est un outil gratuit pour télécharger des vidéos TikTok pour un usage personnel uniquement.',
    termsSec2Title: '2. Propriété intellectuelle',
    termsSec2Content: 'Le droit d\'auteur appartient aux propriétaires du contenu original. Une autorisation doit être obtenue avant le téléchargement.',
    termsSec3Title: '3. Utilisation autorisée',
    termsSec3Content: 'L\'utilisation de bots ou la surcharge des serveurs est interdite.',
    termsSec4Title: '4. Clause de non-responsabilité',
    termsSec4Content: 'Le service est fourni "tel quel" sans garantie.',
    termsSec5Title: '5. Modifications',
    termsSec5Content: 'Nous nous réservons le droit de modifier ces conditions à tout moment.'
  },
  de: {
    heroTitlePart1: 'TikTok Video Herunterladen ',
    heroTitlePart2: 'Ohne Wasserzeichen',
    heroDesc: 'Der beste Weg, um TikTok-Videos kostenlos in hoher Qualität herunterzuladen. Keine Software nötig!',
    inputPlaceholder: 'Fügen Sie den TikTok-Link hier ein...',
    downloadBtn: 'Herunterladen',
    processing: 'Verarbeitung...',
    fetchingData: 'Daten werden abgerufen...',
    emptyInputError: 'Bitte zuerst einen TikTok-Link eingeben',
    successMsg: 'Video erfolgreich vorbereitet!',
    termsAgreement: 'Durch die Nutzung unseres Dienstes stimmen Sie unseren <a class="text-blue-500 hover:underline" href="/terms-of-service">Nutzungsbedingungen</a> zu.',
    videoQuality: 'Video Herunterladen (HD / Ohne)',
    musicQuality: 'Musik Herunterladen (MP3)',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    allRightsReserved: 'Alle Rechte vorbehalten',
    footerDesc: 'Das beste kostenlose Tool zum Herunterladen von TikTok-Videos ohne Wasserzeichen.',
    historyTitle: 'Download-Verlauf',
    clearHistory: 'Alles löschen',
    removeFromHistoryAria: 'Aus Verlauf entfernen',
    reDownload: 'Erneut herunterladen',
    featuresTitle: 'Warum SavePro für TikTok-Downloads wählen?',
    featuresDesc: 'Der beste kostenlose TikTok-Downloader mit erweiterten Funktionen.',
    featureFastTitle: 'Schneller Download',
    featureFastDesc: 'Superschnelle Downloads ohne lange Wartezeiten.',
    featureNoWatermarkTitle: 'Kein Wasserzeichen',
    featureNoWatermarkDesc: 'Erhalten Sie saubere TikTok-Videos ohne Wasserzeichen.',
    featureMusicTitle: 'Musik herunterladen',
    featureMusicDesc: 'Laden Sie TikTok-Musik im hochwertigen MP3-Format herunter.',
    howItWorksTitle: 'Wie lädt man TikTok-Videos herunter?',
    howItWorksDesc: 'Einfache Schritte zum Herunterladen eines Videos mit SavePro.',
    step1Title: 'Link kopieren',
    step1Desc: 'Kopieren Sie den Videolink aus der TikTok-App oder von der Website.',
    step2Title: 'Link einfügen',
    step2Desc: 'Fügen Sie den Link in das SavePro-Suchfeld ein.',
    step3Title: 'Video herunterladen',
    step3Desc: 'Klicken Sie auf Download und erhalten Sie Ihr Video sofort.',
    faqTitle: 'FAQ',
    faqDesc: 'Antworten auf häufig gestellte Fragen zu SavePro.',
    faq1Q: 'Ist SavePro kostenlos?',
    faq1A: 'Ja, SavePro ist völlig kostenlos und verlangt keine Gebühren.',
    faq2Q: 'Kann ich auf dem iPhone/iPad herunterladen?',
    faq2A: 'Ja! Unter iOS empfehlen wir die Verwendung von Safari für einfache Downloads.',
    faq3Q: 'Ist es wirklich ohne Wasserzeichen?',
    faq3A: 'Ja, unser Hauptmerkmal ist das vollständige Entfernen des Wasserzeichens.',
    faq4Q: 'Muss ich etwas installieren?',
    faq4A: 'Nein, SavePro funktioniert direkt im Browser.',
    faq5Q: 'Wie ist die Videoqualität?',
    faq5A: 'Videos werden in der höchsten verfügbaren Qualität (HD) heruntergeladen.',
    historyCleared: 'Verlauf gelöscht',
    videoNotAvailable: 'Videolink nicht verfügbar',
    musicNotAvailable: 'Musiklink nicht verfügbar',
    downloadingVideo: 'Video wird heruntergeladen...',
    downloadingMusic: 'Musik wird heruntergeladen...',
    downloadFailed: 'Download fehlgeschlagen (HTTP {status})',
    fileTooSmall: 'Datei zu klein – Link ist möglicherweise abgelaufen',
    downloadSuccess: 'Erfolgreich heruntergeladen!',
    downloadFailedGeneric: 'Download fehlgeschlagen, versuchen Sie es erneut',
    loading: 'Laden...',
    privacyPolicyTitle: 'Datenschutzrichtlinie',
    privacyPolicyIntro: 'Bei SavePro verpflichten wir uns, Ihre Privatsphäre zu schützen und zu respektieren. Diese Richtlinie erklärt, wie wir Informationen sammeln und verwenden.',
    privacySec1Title: '1. Informationen, die wir sammeln',
    privacySec1Content: 'Wir sammeln keine persönlichen Informationen wie Name oder E-Mail. Wir sammeln möglicherweise nicht-personenbezogene Daten wie IP-Adresse und Browsertyp.',
    privacySec2Title: '2. Wie wir Ihre Informationen verwenden',
    privacySec2Content: 'Die Informationen werden verwendet, um die Servicequalität zu verbessern und die Sicherheit der Website zu gewährleisten.',
    privacySec3Title: '3. Cookies',
    privacySec3Content: 'Wir verwenden Cookies, um die Benutzererfahrung zu verbessern und personalisierte Werbung anzuzeigen.',
    privacySec4Title: '4. Weitergabe von Informationen',
    privacySec4Content: 'Wir geben Ihre Informationen nicht an Dritte weiter, es sei denn, dies ist gesetzlich vorgeschrieben.',
    privacySec5Title: '5. Anzeigen und externe Links',
    privacySec5Content: 'Unsere Website kann Anzeigen von Google AdSense und Links zu externen Websites enthalten.',
    privacySec6Title: '6. Richtlinienänderungen',
    privacySec6Content: 'Wir behalten uns das Recht vor, diese Richtlinie jederzeit zu aktualisieren.',
    privacyContactTitle: 'Kontaktieren Sie uns',
    privacyContactContent: 'Wenn Sie Fragen haben, kontaktieren Sie uns unter:',
    termsTitle: 'Nutzungsbedingungen',
    termsIntro: 'Durch die Nutzung von SavePro stimmen Sie diesen Geschäftsbedingungen zu.',
    termsSec1Title: '1. Art des Dienstes',
    termsSec1Content: 'SavePro ist ein kostenloses Tool zum Herunterladen von TikTok-Videos ausschließlich für den persönlichen Gebrauch.',
    termsSec2Title: '2. Geistiges Eigentum',
    termsSec2Content: 'Das Urheberrecht liegt bei den ursprünglichen Inhaltseigentümern. Vor dem Herunterladen muss eine Erlaubnis eingeholt werden.',
    termsSec3Title: '3. Zulässige Nutzung',
    termsSec3Content: 'Die Verwendung von Bots oder das Überlasten von Servern ist untersagt.',
    termsSec4Title: '4. Haftungsausschluss',
    termsSec4Content: 'Der Dienst wird ohne Mängelgewähr bereitgestellt.',
    termsSec5Title: '5. Änderungen',
    termsSec5Content: 'Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern.'
  },
  tr: {
    heroTitlePart1: 'TikTok Videosu İndir ',
    heroTitlePart2: 'Filigransız',
    heroDesc: 'TikTok videolarını yüksek kalitede ücretsiz indirmenin en iyi yolu. Yazılıma gerek yok, sadece bağlantıyı yapıştırın!',
    inputPlaceholder: 'TikTok video bağlantısını buraya yapıştırın...',
    downloadBtn: 'İndir',
    processing: 'İşleniyor...',
    fetchingData: 'Sunucudan veriler alınıyor...',
    emptyInputError: 'Lütfen önce bir TikTok bağlantısı girin',
    successMsg: 'Video başarıyla hazırlandı!',
    termsAgreement: 'Hizmetimizi kullanarak <a class="text-blue-500 hover:underline" href="/terms-of-service">Kullanım Şartlarımızı</a> kabul etmiş olursunuz.',
    videoQuality: 'Videoyu İndir (HD / Filigransız)',
    musicQuality: 'Müziği İndir (MP3)',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Hizmet Şartları',
    allRightsReserved: 'Tüm hakları saklıdır',
    footerDesc: 'TikTok videolarını filigransız indirmek için en iyi ücretsiz araç.',
    historyTitle: 'İndirme Geçmişi',
    clearHistory: 'Hepsini Temizle',
    removeFromHistoryAria: 'Geçmişten kaldır',
    reDownload: 'Yeniden indir',
    featuresTitle: 'TikTok indirmeleri için neden SavePro\'yu seçmelisiniz?',
    featuresDesc: 'Gelişmiş özelliklere sahip en iyi ücretsiz TikTok indiricisi.',
    featureFastTitle: 'Hızlı İndirme',
    featureFastDesc: 'Uzun bekleme süreleri olmadan süper hızlı indirmeler.',
    featureNoWatermarkTitle: 'Filigransız',
    featureNoWatermarkDesc: 'Herhangi bir filigran olmadan temiz TikTok videoları alın.',
    featureMusicTitle: 'Müzik İndir',
    featureMusicDesc: 'TikTok müziklerini yüksek kaliteli MP3 formatında indirin.',
    howItWorksTitle: 'TikTok videoları nasıl indirilir?',
    howItWorksDesc: 'SavePro kullanarak herhangi bir videoyu indirmek için basit adımlar.',
    step1Title: 'Bağlantıyı Kopyala',
    step1Desc: 'Video bağlantısını TikTok uygulamasından veya web sitesinden kopyalayın.',
    step2Title: 'Bağlantıyı Yapıştır',
    step2Desc: 'Bağlantıyı SavePro arama kutusuna yapıştırın.',
    step3Title: 'Videoyu İndir',
    step3Desc: 'İndir\'e tıklayın ve videonuzu anında alın.',
    faqTitle: 'SSS',
    faqDesc: 'SavePro hakkında sıkça sorulan soruların yanıtları.',
    faq1Q: 'SavePro ücretsiz mi?',
    faq1A: 'Evet, SavePro tamamen ücretsizdir ve herhangi bir ücret talep etmez.',
    faq2Q: 'iPhone/iPad\'e indirebilir miyim?',
    faq2A: 'Evet! iOS kullanıyorsanız, kolay indirmeler için Safari kullanmanızı öneririz.',
    faq3Q: 'Gerçekten filigransız mı?',
    faq3A: 'Evet, ana özelliğimiz filigranı tamamen kaldırmaktır.',
    faq4Q: 'Bir şey yüklemem gerekiyor mu?',
    faq4A: 'Hayır, SavePro doğrudan tarayıcıda çalışır.',
    faq5Q: 'Video kalitesi nedir?',
    faq5A: 'Videolar mevcut en yüksek kalitede (HD) indirilir.',
    historyCleared: 'Geçmiş temizlendi',
    videoNotAvailable: 'Video bağlantısı mevcut değil',
    musicNotAvailable: 'Müzik bağlantısı mevcut değil',
    downloadingVideo: 'Video indiriliyor...',
    downloadingMusic: 'Müzik indiriliyor...',
    downloadFailed: 'İndirme başarısız (HTTP {status})',
    fileTooSmall: 'Dosya çok küçük - bağlantı süresi dolmuş olabilir',
    downloadSuccess: 'Başarıyla indirildi!',
    downloadFailedGeneric: 'İndirme başarısız, tekrar deneyin',
    loading: 'Yükleniyor...',
    privacyPolicyTitle: 'Gizlilik Politikası',
    privacyPolicyIntro: 'SavePro olarak gizliliğinizi korumaya ve saygı duymaya kararlıyız. Bu politika, bilgileri nasıl topladığımızı ve kullandığımızı açıklar.',
    privacySec1Title: '1. Topladığımız Bilgiler',
    privacySec1Content: 'İsim veya e-posta gibi kişisel bilgileri toplamıyoruz. IP adresi ve tarayıcı türü gibi kişisel olmayan verileri toplayabiliriz.',
    privacySec2Title: '2. Bilgilerinizi Nasıl Kullanıyoruz',
    privacySec2Content: 'Bilgiler, hizmet kalitesini artırmak ve site güvenliğini sağlamak için kullanılır.',
    privacySec3Title: '3. Çerezler',
    privacySec3Content: 'Kullanıcı deneyimini iyileştirmek ve kişiselleştirilmiş reklamlar göstermek için çerezleri kullanıyoruz.',
    privacySec4Title: '4. Bilgi Paylaşımı',
    privacySec4Content: 'Yasaların gerektirdiği durumlar haricinde bilgilerinizi üçüncü taraflarla paylaşmıyoruz.',
    privacySec5Title: '5. Reklamlar ve Dış Bağlantılar',
    privacySec5Content: 'Sitemiz Google AdSense reklamları ve dış sitelere bağlantılar içerebilir.',
    privacySec6Title: '6. Politika Değişiklikleri',
    privacySec6Content: 'Bu politikayı istediğimiz zaman güncelleme hakkını saklı tutuyoruz.',
    privacyContactTitle: 'Bize Ulaşın',
    privacyContactContent: 'Herhangi bir sorunuz varsa, bizimle iletişime geçin:',
    termsTitle: 'Hizmet Şartları',
    termsIntro: 'SavePro\'yu kullanarak bu şart ve koşulları kabul etmiş olursunuz.',
    termsSec1Title: '1. Hizmetin Doğası',
    termsSec1Content: 'SavePro, TikTok videolarını yalnızca kişisel kullanım için indirmeye yönelik ücretsiz bir araçtır.',
    termsSec2Title: '2. Fikri Mülkiyet',
    termsSec2Content: 'Telif hakkı orijinal içerik sahiplerine aittir. İndirmeden önce izin alınmalıdır.',
    termsSec3Title: '3. İzin Verilen Kullanım',
    termsSec3Content: 'Bot kullanımı veya sunucuların aşırı yüklenmesi yasaktır.',
    termsSec4Title: '4. Feragatname',
    termsSec4Content: 'Hizmet "olduğu gibi" sunulmaktadır.',
    termsSec5Title: '5. Değişiklikler',
    termsSec5Content: 'Bu şartları istediğimiz zaman değiştirme hakkını saklı tutuyoruz.'
  },
  zh: {
    heroTitlePart1: '下载 TikTok 视频 ',
    heroTitlePart2: '无水印',
    heroDesc: '免费下载高质量 TikTok 视频的最佳方式。无需安装软件，只需复制链接即可下载！',
    inputPlaceholder: '在此处粘贴 TikTok 视频链接...',
    downloadBtn: '下载',
    processing: '处理中...',
    fetchingData: '正在从服务器获取数据...',
    emptyInputError: '请先输入 TikTok 链接',
    successMsg: '视频准备成功！',
    termsAgreement: '使用我们的服务即表示您同意我们的<a class="text-blue-500 hover:underline" href="/terms-of-service">使用条款</a>。',
    videoQuality: '下载视频 (高清 / 无水印)',
    musicQuality: '下载音乐 (MP3)',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    allRightsReserved: '版权所有',
    footerDesc: '下载无水印 TikTok 视频的最佳免费工具。',
    historyTitle: '下载历史',
    clearHistory: '全部清除',
    removeFromHistoryAria: '从历史记录中删除',
    reDownload: '重新下载',
    featuresTitle: '为什么选择 SavePro 下载 TikTok？',
    featuresDesc: '具有先进功能的最佳免费 TikTok 下载器。',
    featureFastTitle: '快速下载',
    featureFastDesc: '超快速下载，无需长时间等待。',
    featureNoWatermarkTitle: '无水印',
    featureNoWatermarkDesc: '获取没有任何水印的干净 TikTok 视频。',
    featureMusicTitle: '下载音乐',
    featureMusicDesc: '下载高质量 MP3 格式的 TikTok 音乐。',
    howItWorksTitle: '如何下载 TikTok 视频？',
    howItWorksDesc: '使用 SavePro 下载任何视频的简单步骤。',
    step1Title: '复制链接',
    step1Desc: '从 TikTok 应用或网站复制视频链接。',
    step2Title: '粘贴链接',
    step2Desc: '将链接粘贴到 SavePro 搜索框中。',
    step3Title: '下载视频',
    step3Desc: '点击下载，立即获取您的视频。',
    faqTitle: '常见问题',
    faqDesc: '有关 SavePro 的常见问题解答。',
    faq1Q: 'SavePro 是免费的吗？',
    faq1A: '是的，SavePro 完全免费，不会收取任何费用。',
    faq2Q: '我可以在 iPhone/iPad 上下载吗？',
    faq2A: '是的！如果您使用 iOS，我们建议使用 Safari 以方便下载。',
    faq3Q: '真的没有水印吗？',
    faq3A: '是的，我们的主要功能是完全去除水印。',
    faq4Q: '我需要安装什么吗？',
    faq4A: '不，SavePro 直接在浏览器中运行。',
    faq5Q: '视频质量如何？',
    faq5A: '视频以最高可用质量 (HD) 下载。',
    historyCleared: '历史记录已清除',
    videoNotAvailable: '视频链接不可用',
    musicNotAvailable: '音乐链接不可用',
    downloadingVideo: '正在下载视频...',
    downloadingMusic: '正在下载音乐...',
    downloadFailed: '下载失败 (HTTP {status})',
    fileTooSmall: '文件太小 - 链接可能已过期',
    downloadSuccess: '下载成功！',
    downloadFailedGeneric: '下载失败，请重试',
    loading: '加载中...',
    privacyPolicyTitle: '隐私政策',
    privacyPolicyIntro: '在 SavePro，我们致力于保护并尊重您的隐私。本政策解释了我们如何收集和使用信息。',
    privacySec1Title: '1. 我们收集的信息',
    privacySec1Content: '我们不收集姓名或电子邮件等个人信息。我们可能会收集 IP 地址和浏览器类型等非个人数据。',
    privacySec2Title: '2. 我们如何使用您的信息',
    privacySec2Content: '这些信息用于提高服务质量并确保网站安全。',
    privacySec3Title: '3. Cookie',
    privacySec3Content: '我们使用 Cookie 来改善用户体验并显示个性化广告。',
    privacySec4Title: '4. 共享信息',
    privacySec4Content: '除非法律要求，否则我们不会与第三方共享您的信息。',
    privacySec5Title: '5. 广告和外部链接',
    privacySec5Content: '我们的网站可能包含来自 Google AdSense 的广告和指向外部网站的链接。',
    privacySec6Title: '6. 政策变更',
    privacySec6Content: '我们保留随时更新本政策的权利。',
    privacyContactTitle: '联系我们',
    privacyContactContent: '如果您有任何问题，请通过以下方式联系我们：',
    termsTitle: '服务条款',
    termsIntro: '通过使用 SavePro，您同意这些条款和条件。',
    termsSec1Title: '1. 服务性质',
    termsSec1Content: 'SavePro 是一个仅供个人使用的 TikTok 视频下载免费工具。',
    termsSec2Title: '2. 知识产权',
    termsSec2Content: '版权归原内容所有者所有。下载前必须获得许可。',
    termsSec3Title: '3. 允许的使用',
    termsSec3Content: '禁止使用机器人或使服务器过载。',
    termsSec4Title: '4. 免责声明',
    termsSec4Content: '服务按“原样”提供，不作任何保证。',
    termsSec5Title: '5. 变更',
    termsSec5Content: '我们保留随时修改这些条款的权利。'
  },
  ru: {
    heroTitlePart1: 'Скачать видео TikTok ',
    heroTitlePart2: 'Без водяных знаков',
    heroDesc: 'Лучший способ бесплатно скачать видео из TikTok в высоком качестве. Программы не нужны, просто вставьте ссылку!',
    inputPlaceholder: 'Вставьте ссылку на видео TikTok здесь...',
    downloadBtn: 'Скачать',
    processing: 'Обработка...',
    fetchingData: 'Получение данных с сервера...',
    emptyInputError: 'Пожалуйста, введите ссылку на TikTok',
    successMsg: 'Видео успешно подготовлено!',
    termsAgreement: 'Используя наш сервис, вы соглашаетесь с <a class="text-blue-500 hover:underline" href="/terms-of-service">Условиями использования</a>.',
    videoQuality: 'Скачать видео (HD / Без знака)',
    musicQuality: 'Скачать музыку (MP3)',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfService: 'Условия использования',
    allRightsReserved: 'Все права защищены',
    footerDesc: 'Лучший бесплатный инструмент для скачивания видео из TikTok без водяных знаков.',
    historyTitle: 'История скачиваний',
    clearHistory: 'Очистить все',
    removeFromHistoryAria: 'Удалить из истории',
    reDownload: 'Скачать заново',
    featuresTitle: 'Почему стоит выбрать SavePro для TikTok?',
    featuresDesc: 'Лучший бесплатный загрузчик TikTok с расширенными функциями.',
    featureFastTitle: 'Быстрая загрузка',
    featureFastDesc: 'Сверхбыстрая загрузка без долгого ожидания.',
    featureNoWatermarkTitle: 'Без водяного знака',
    featureNoWatermarkDesc: 'Получайте чистые видео из TikTok без водяных знаков.',
    featureMusicTitle: 'Скачать музыку',
    featureMusicDesc: 'Скачивайте музыку из TikTok в высоком качестве в формате MP3.',
    howItWorksTitle: 'Как скачивать видео из TikTok?',
    howItWorksDesc: 'Простые шаги для скачивания любого видео с помощью SavePro.',
    step1Title: 'Скопируйте ссылку',
    step1Desc: 'Скопируйте ссылку на видео из приложения или сайта TikTok.',
    step2Title: 'Вставьте ссылку',
    step2Desc: 'Вставьте ссылку в поле поиска SavePro.',
    step3Title: 'Скачайте видео',
    step3Desc: 'Нажмите «Скачать» и мгновенно получите свое видео.',
    faqTitle: 'Часто задаваемые вопросы',
    faqDesc: 'Ответы на популярные вопросы о SavePro.',
    faq1Q: 'SavePro бесплатный?',
    faq1A: 'Да, SavePro полностью бесплатен и не требует оплаты.',
    faq2Q: 'Могу ли я скачивать на iPhone/iPad?',
    faq2A: 'Да! На iOS мы рекомендуем использовать Safari для удобного скачивания.',
    faq3Q: 'Это действительно без водяного знака?',
    faq3A: 'Да, наша главная особенность — полное удаление водяного знака.',
    faq4Q: 'Нужно ли мне что-то устанавливать?',
    faq4A: 'Нет, SavePro работает прямо в браузере.',
    faq5Q: 'Какое качество видео?',
    faq5A: 'Видео скачиваются в максимально доступном качестве (HD).',
    historyCleared: 'История очищена',
    videoNotAvailable: 'Ссылка на видео недоступна',
    musicNotAvailable: 'Ссылка на музыку недоступна',
    downloadingVideo: 'Загрузка видео...',
    downloadingMusic: 'Загрузка музыки...',
    downloadFailed: 'Ошибка загрузки (HTTP {status})',
    fileTooSmall: 'Файл слишком мал — возможно, ссылка истекла',
    downloadSuccess: 'Успешно скачано!',
    downloadFailedGeneric: 'Ошибка загрузки, попробуйте еще раз',
    loading: 'Загрузка...',
    privacyPolicyTitle: 'Политика конфиденциальности',
    privacyPolicyIntro: 'В SavePro мы стремимся защищать и уважать вашу конфиденциальность. Эта политика объясняет, как мы собираем и используем информацию.',
    privacySec1Title: '1. Информация, которую мы собираем',
    privacySec1Content: 'Мы не собираем личную информацию, такую как имя или адрес электронной почты. Мы можем собирать неперсональные данные, такие как IP-адрес и тип браузера.',
    privacySec2Title: '2. Как мы используем вашу информацию',
    privacySec2Content: 'Информация используется для улучшения качества обслуживания и обеспечения безопасности сайта.',
    privacySec3Title: '3. Файлы cookie',
    privacySec3Content: 'Мы используем файлы cookie для улучшения пользовательского опыта и показа персонализированной рекламы.',
    privacySec4Title: '4. Обмен информацией',
    privacySec4Content: 'Мы не передаем вашу информацию третьим лицам, за исключением случаев, предусмотренных законом.',
    privacySec5Title: '5. Реклама и внешние ссылки',
    privacySec5Content: 'Наш сайт может содержать рекламу Google AdSense и ссылки на внешние сайты.',
    privacySec6Title: '6. Изменения в политике',
    privacySec6Content: 'Мы оставляем за собой право обновлять эту политику в любое время.',
    privacyContactTitle: 'Свяжитесь с нами',
    privacyContactContent: 'Если у вас есть вопросы, свяжитесь с нами по адресу:',
    termsTitle: 'Условия использования',
    termsIntro: 'Используя SavePro, вы соглашаетесь с этими условиями.',
    termsSec1Title: '1. Характер услуги',
    termsSec1Content: 'SavePro — это бесплатный инструмент для скачивания видео из TikTok только для личного использования.',
    termsSec2Title: '2. Интеллектуальная собственность',
    termsSec2Content: 'Авторские права принадлежат оригинальным владельцам контента. Перед скачиванием необходимо получить разрешение.',
    termsSec3Title: '3. Разрешенное использование',
    termsSec3Content: 'Использование ботов или перегрузка серверов запрещены.',
    termsSec4Title: '4. Отказ от ответственности',
    termsSec4Content: 'Услуга предоставляется «как есть» без гарантий.',
    termsSec5Title: '5. Изменения',
    termsSec5Content: 'Мы оставляем за собой право изменять эти условия в любое время.'
  },
  hi: {
    heroTitlePart1: 'टिकटॉक वीडियो डाउनलोड करें ',
    heroTitlePart2: 'बिना वॉटरमार्क के',
    heroDesc: 'उच्च गुणवत्ता में मुफ्त में टिकटॉक वीडियो डाउनलोड करने का सबसे अच्छा तरीका। कोई सॉफ्टवेयर नहीं चाहिए!',
    inputPlaceholder: 'यहाँ टिकटॉक वीडियो लिंक पेस्ट करें...',
    downloadBtn: 'डाउनलोड',
    processing: 'प्रक्रिया हो रही है...',
    fetchingData: 'सर्वर से डेटा प्राप्त किया जा रहा है...',
    emptyInputError: 'कृपया पहले एक टिकटॉक लिंक दर्ज करें',
    successMsg: 'वीडियो सफलतापूर्वक तैयार किया गया!',
    termsAgreement: 'हमारी सेवा का उपयोग करके, आप हमारी <a class="text-blue-500 hover:underline" href="/terms-of-service">उपयोग की शर्तों</a> से सहमत होते हैं।',
    videoQuality: 'वीडियो डाउनलोड करें (HD / कोई वॉटरमार्क नहीं)',
    musicQuality: 'संगीत डाउनलोड करें (MP3)',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    footerDesc: 'वॉटरमार्क के बिना टिकटॉक वीडियो डाउनलोड करने के लिए सबसे अच्छा मुफ्त उपकरण।',
    historyTitle: 'डाउनलोड इतिहास',
    clearHistory: 'सभी साफ करें',
    removeFromHistoryAria: 'इतिहास से हटाएँ',
    reDownload: 'फिर से डाउनलोड करें',
    featuresTitle: 'टिकटॉक डाउनलोड के लिए SavePro क्यों चुनें?',
    featuresDesc: 'उन्नत सुविधाओं के साथ सबसे अच्छा मुफ्त टिकटॉक डाउनलोडर।',
    featureFastTitle: 'तेजी से डाउनलोड',
    featureFastDesc: 'बिना लंबे इंतजार के सुपर फास्ट डाउनलोड।',
    featureNoWatermarkTitle: 'कोई वॉटरमार्क नहीं',
    featureNoWatermarkDesc: 'बिना किसी वॉटरमार्क के साफ टिकटॉक वीडियो प्राप्त करें।',
    featureMusicTitle: 'संगीत डाउनलोड करें',
    featureMusicDesc: 'उच्च गुणवत्ता वाले MP3 प्रारूप में टिकटॉक संगीत डाउनलोड करें।',
    howItWorksTitle: 'टिकटॉक वीडियो कैसे डाउनलोड करें?',
    howItWorksDesc: 'SavePro का उपयोग करके किसी भी वीडियो को डाउनलोड करने के लिए सरल कदम।',
    step1Title: 'लिंक कॉपी करें',
    step1Desc: 'टिकटॉक ऐप या वेबसाइट से वीडियो लिंक कॉपी करें।',
    step2Title: 'लिंक पेस्ट करें',
    step2Desc: 'SavePro सर्च बॉक्स में लिंक पेस्ट करें।',
    step3Title: 'वीडियो डाउनलोड करें',
    step3Desc: 'डाउनलोड पर क्लिक करें और तुरंत अपना वीडियो प्राप्त करें।',
    faqTitle: 'सामान्य प्रश्न',
    faqDesc: 'SavePro के बारे में सामान्य प्रश्नों के उत्तर।',
    faq1Q: 'क्या SavePro मुफ्त है?',
    faq1A: 'हाँ, SavePro पूरी तरह से मुफ्त है और कोई शुल्क नहीं मांगेगा।',
    faq2Q: 'क्या मैं iPhone/iPad पर डाउनलोड कर सकता हूँ?',
    faq2A: 'हाँ! यदि आप iOS पर हैं, तो हम आसान डाउनलोड के लिए Safari का उपयोग करने की सलाह देते हैं।',
    faq3Q: 'क्या यह वास्तव में वॉटरमार्क के बिना है?',
    faq3A: 'हाँ, हमारी मुख्य विशेषता वॉटरमार्क को पूरी तरह से हटाना है।',
    faq4Q: 'क्या मुझे कुछ इंस्टॉल करने की आवश्यकता है?',
    faq4A: 'नहीं, SavePro सीधे ब्राउज़र में काम करता है।',
    faq5Q: 'वीडियो की गुणवत्ता क्या है?',
    faq5A: 'वीडियो उच्चतम उपलब्ध गुणवत्ता (HD) में डाउनलोड किए जाते हैं।',
    historyCleared: 'इतिहास साफ किया गया',
    videoNotAvailable: 'वीडियो लिंक उपलब्ध नहीं है',
    musicNotAvailable: 'संगीत लिंक उपलब्ध नहीं है',
    downloadingVideo: 'वीडियो डाउनलोड हो रहा है...',
    downloadingMusic: 'संगीत डाउनलोड हो रहा है...',
    downloadFailed: 'डाउनलोड विफल (HTTP {status})',
    fileTooSmall: 'फ़ाइल बहुत छोटी है — लिंक समाप्त हो सकता है',
    downloadSuccess: 'सफलतापूर्वक डाउनलोड किया गया!',
    downloadFailedGeneric: 'डाउनलोड विफल, फिर से प्रयास करें',
    loading: 'लोड हो रहा है...',
    privacyPolicyTitle: 'गोपनीयता नीति',
    privacyPolicyIntro: 'SavePro में, हम आपकी गोपनीयता की रक्षा और सम्मान करने के लिए प्रतिबद्ध हैं। यह नीति बताती है कि हम जानकारी कैसे एकत्र करते हैं और उसका उपयोग करते हैं।',
    privacySec1Title: '1. जानकारी जो हम एकत्र करते हैं',
    privacySec1Content: 'हम नाम या ईमेल जैसी व्यक्तिगत जानकारी एकत्र नहीं करते हैं। हम आईपी एड्रेस और ब्राउज़र प्रकार जैसे गैर-व्यक्तिगत डेटा एकत्र कर सकते हैं।',
    privacySec2Title: '2. हम आपकी जानकारी का उपयोग कैसे करते हैं',
    privacySec2Content: 'जानकारी का उपयोग सेवा की गुणवत्ता में सुधार करने और साइट सुरक्षा सुनिश्चित करने के लिए किया जाता है।',
    privacySec3Title: '3. कुकीज़',
    privacySec3Content: 'हम उपयोगकर्ता अनुभव को बेहतर बनाने और व्यक्तिगत विज्ञापन प्रदर्शित करने के लिए कुकीज़ का उपयोग करते हैं।',
    privacySec4Title: '4. जानकारी साझा करना',
    privacySec4Content: 'हम कानून द्वारा आवश्यक के अलावा आपकी जानकारी तीसरे पक्ष के साथ साझा नहीं करते हैं।',
    privacySec5Title: '5. विज्ञापन और बाहरी लिंक',
    privacySec5Content: 'हमारी साइट में Google AdSense के विज्ञापन और बाहरी साइटों के लिंक हो सकते हैं।',
    privacySec6Title: '6. नीति में परिवर्तन',
    privacySec6Content: 'हम किसी भी समय इस नीति को अपडेट करने का अधिकार सुरक्षित रखते हैं।',
    privacyContactTitle: 'संपर्क करें',
    privacyContactContent: 'यदि आपके कोई प्रश्न हैं, तो हमसे यहां संपर्क करें:',
    termsTitle: 'सेवा की शर्तें',
    termsIntro: 'SavePro का उपयोग करके, आप इन नियमों और शर्तों से सहमत होते हैं।',
    termsSec1Title: '1. सेवा की प्रकृति',
    termsSec1Content: 'SavePro केवल व्यक्तिगत उपयोग के लिए टिकटॉक वीडियो डाउनलोड करने का एक मुफ्त उपकरण है।',
    termsSec2Title: '2. बौद्धिक संपदा',
    termsSec2Content: 'कॉपीराइट मूल सामग्री स्वामियों का है। डाउनलोड करने से पहले अनुमति प्राप्त की जानी चाहिए।',
    termsSec3Title: '3. अनुमत उपयोग',
    termsSec3Content: 'बॉट्स का उपयोग या सर्वर पर ओवरलोडिंग प्रतिबंधित है।',
    termsSec4Title: '4. अस्वीकरण',
    termsSec4Content: 'सेवा बिना किसी वारंटी के "जैसी है" वैसी ही प्रदान की जाती है।',
    termsSec5Title: '5. परिवर्तन',
    termsSec5Content: 'हम किसी भी समय इन शर्तों को संशोधित करने का अधिकार सुरक्षित रखते हैं।'
  },
  pt: {
    heroTitlePart1: 'Baixar Vídeo do TikTok ',
    heroTitlePart2: 'Sem Marca D\'água',
    heroDesc: 'A melhor forma de baixar vídeos do TikTok grátis em alta qualidade. Nenhum software necessário!',
    inputPlaceholder: 'Cole o link do vídeo do TikTok aqui...',
    downloadBtn: 'Baixar',
    processing: 'Processando...',
    fetchingData: 'Buscando dados do servidor...',
    emptyInputError: 'Por favor, insira um link do TikTok primeiro',
    successMsg: 'Vídeo preparado com sucesso!',
    termsAgreement: 'Ao usar nosso serviço, você concorda com nossos <a class="text-blue-500 hover:underline" href="/terms-of-service">Termos de Uso</a>.',
    videoQuality: 'Baixar Vídeo (HD / Sem Marca)',
    musicQuality: 'Baixar Música (MP3)',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    allRightsReserved: 'Todos os direitos reservados',
    footerDesc: 'A melhor ferramenta gratuita para baixar vídeos do TikTok sem marca d\'água.',
    historyTitle: 'Histórico de Downloads',
    clearHistory: 'Limpar Tudo',
    removeFromHistoryAria: 'Remover do histórico',
    reDownload: 'Baixar novamente',
    featuresTitle: 'Por que escolher o SavePro para downloads do TikTok?',
    featuresDesc: 'O melhor baixador gratuito de TikTok com recursos avançados.',
    featureFastTitle: 'Download Rápido',
    featureFastDesc: 'Downloads super rápidos sem longos tempos de espera.',
    featureNoWatermarkTitle: 'Sem Marca D\'água',
    featureNoWatermarkDesc: 'Obtenha vídeos do TikTok limpos sem nenhuma marca d\'água.',
    featureMusicTitle: 'Baixar Música',
    featureMusicDesc: 'Baixe músicas do TikTok em formato MP3 de alta qualidade.',
    howItWorksTitle: 'Como baixar vídeos do TikTok?',
    howItWorksDesc: 'Passos simples para baixar qualquer vídeo usando o SavePro.',
    step1Title: 'Copiar Link',
    step1Desc: 'Copie o link do vídeo do aplicativo ou site do TikTok.',
    step2Title: 'Colar Link',
    step2Desc: 'Cole o link na caixa de pesquisa do SavePro.',
    step3Title: 'Baixar Vídeo',
    step3Desc: 'Clique em baixar e obtenha seu vídeo instantaneamente.',
    faqTitle: 'Perguntas Frequentes',
    faqDesc: 'Respostas para perguntas comuns sobre o SavePro.',
    faq1Q: 'O SavePro é gratuito?',
    faq1A: 'Sim, o SavePro é completamente gratuito e não cobrará nenhuma taxa.',
    faq2Q: 'Posso baixar no iPhone/iPad?',
    faq2A: 'Sim! Se você estiver no iOS, recomendamos usar o Safari para downloads fáceis.',
    faq3Q: 'É realmente sem marca d\'água?',
    faq3A: 'Sim, nosso principal recurso é remover a marca d\'água completamente.',
    faq4Q: 'Preciso instalar algo?',
    faq4A: 'Não, o SavePro funciona diretamente no navegador.',
    faq5Q: 'Qual é a qualidade do vídeo?',
    faq5A: 'Os vídeos são baixados na melhor qualidade disponível (HD).',
    historyCleared: 'Histórico limpo',
    videoNotAvailable: 'Link do vídeo não disponível',
    musicNotAvailable: 'Link da música não disponível',
    downloadingVideo: 'Baixando vídeo...',
    downloadingMusic: 'Baixando música...',
    downloadFailed: 'Falha no download (HTTP {status})',
    fileTooSmall: 'Arquivo muito pequeno — o link pode ter expirado',
    downloadSuccess: 'Baixado com sucesso!',
    downloadFailedGeneric: 'Falha no download, tente novamente',
    loading: 'Carregando...',
    privacyPolicyTitle: 'Política de Privacidade',
    privacyPolicyIntro: 'No SavePro, estamos comprometidos em proteger e respeitar sua privacidade. Esta política explica como coletamos e usamos as informações.',
    privacySec1Title: '1. Informações que Coletamos',
    privacySec1Content: 'Não coletamos informações pessoais como nome ou e-mail. Podemos coletar dados não pessoais, como endereço IP e tipo de navegador.',
    privacySec2Title: '2. Como Usamos Suas Informações',
    privacySec2Content: 'As informações são usadas para melhorar a qualidade do serviço e garantir a segurança do site.',
    privacySec3Title: '3. Cookies',
    privacySec3Content: 'Usamos cookies para melhorar a experiência do usuário e exibir anúncios personalizados.',
    privacySec4Title: '4. Compartilhamento de Informações',
    privacySec4Content: 'Não compartilhamos suas informações com terceiros, exceto conforme exigido por lei.',
    privacySec5Title: '5. Anúncios e Links Externos',
    privacySec5Content: 'Nosso site pode conter anúncios do Google AdSense e links para sites externos.',
    privacySec6Title: '6. Alterações na Política',
    privacySec6Content: 'Reservamo-nos o direito de atualizar esta política a qualquer momento.',
    privacyContactTitle: 'Contate-nos',
    privacyContactContent: 'Se você tiver alguma dúvida, entre em contato conosco em:',
    termsTitle: 'Termos de Serviço',
    termsIntro: 'Ao usar o SavePro, você concorda com estes termos e condições.',
    termsSec1Title: '1. Natureza do Serviço',
    termsSec1Content: 'O SavePro é uma ferramenta gratuita para baixar vídeos do TikTok apenas para uso pessoal.',
    termsSec2Title: '2. Propriedade Intelectual',
    termsSec2Content: 'Os direitos autorais pertencem aos proprietários originais do conteúdo. A permissão deve ser obtida antes de baixar.',
    termsSec3Title: '3. Uso Permitido',
    termsSec3Content: 'O uso de bots ou sobrecarga de servidores é proibido.',
    termsSec4Title: '4. Isenção de Responsabilidade',
    termsSec4Content: 'O serviço é fornecido "como está", sem garantias.',
    termsSec5Title: '5. Alterações',
    termsSec5Content: 'Reservamo-nos o direito de modificar estes termos a qualquer momento.'
  }
};
